config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    get 'edit_email/:id', to: 'registrations#edit_email', as: 'edit_email'
    patch 'update_email/:id', to: 'registrations#update_email', as: 'update_email'
  end
  root to: 'questions#index'
  concern :vote do
    post :vote_up, on: :member
    post :vote_down, on: :member
  end
  resources :subscriptions, only: %i[create destroy]
  resources :files, only: :destroy
  resources :links, only: %i[destroy]
  resources :comments, only: %i[create destroy]
  resources :rewards, only: %i[index]
  resources :questions, concerns: [:vote], shallow: true do
    resources :answers, concerns: [:vote], only: %i[create update destroy] do
      patch :best, on: :member
      patch :reward, on: :member
    end
  end
  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create], shallow: true do
        resources :answers, only: %i[index show create]
      end
    end
  end
  get 'search', to: 'search#index'
  # mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :votes, dependent: :destroy, as: :votable
  belongs_to :user
  has_many :answers, dependent: :destroy
  validates :title, :body, presence: true
  has_many_attached :files
  has_many :links, dependent: :destroy, as: :linkable
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  has_one :reward
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  has_many :comments, as: :commentable, dependent: :destroy
  accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true

  has_many :subscriptions, dependent: :destroy

  def vote_result
    votes.sum(:value)
  end
  after_create :create_subscription

  private

  def create_subscription
    subscriptions.create(user_id: user_id)
  end
end

app/controllers/api/v1/questions_controller.rb
module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      authorize_resource

      def index
        @questions = Question.all
        render json: @questions
      end

      def show
        render json: question
      end

      def create
        @question = current_resource_owner.questions.new(question_params)
          render json: @question
      end

      def update
        if question.update(question_params)
          render json: question
        else
          head :unprocessable_entity
        end
      end

      def destroy
        head :ok if question.destroy
      end

      private

      def question
        @question ||= Question.find(params[:id])
      end

      def question_params
        params.require(:question).permit(:title, :body)
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :question, only: %i[show edit update destroy]
  before_action :subscription, only: %i[show update]
  after_action :publish_question, only: :create
  authorize_resource
  include Votes

  def index
    @questions = Question.all
  end

  def show
    @answer = question.answers.new

  end

  def new
    @question = current_user.questions.new
  end

  def edit; end

  def update
    @question.update(question_params)
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def destroy
      @question.destroy
      redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body,
                                     files: [], links_attributes: %i[_destroy id name link], reward_attributes: %i[id title image])
  end

  def subscription
    @subscription = @question.subscriptions.find_by(user: current_user)
  end

  def question
    @question ||= params[:id] ? Question.find(params[:id]) : Question.new
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      "questions",
      {
        question: ApplicationController.render(
          locals: { question: @question,
                    current_user: current_user,
          },
          partial: 'questions/question'
        )
      }
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with(model: [@user, @question], local: true) do |f|
  = render 'shared/errors', resource: @question
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.file_field :files, multiple: true

  p
    = f.fields_for :reward do |reward|
      = render "reward_nested_fields", f: reward
  p
    - unless @question.reward
      .reward
        = link_to_add_association "Награды", f, "reward",
                partial: "reward_nested_fields",class: "add-reward-link",id: "add-reward-link"
  p
    = f.fields_for :links do |link|
      = render "partials/links_nested_fields", f: link
  p
    = link_to_add_association "Ссылки", f, "links",
            class: 'create_object',
            partial: "partials/links_nested_fields"
  p
    = f.submit 'Ask'
javascript:
    $('.reward').on('click', '.add-reward-link', function (e) {
        $('.add-reward-link').addClass('hidden')
    })

app/views/questions/_question.html.slim
.question id = "#{question.id}"
  p= question.title
  p= link_to 'Show', question

app/views/questions/_reward_nested_fields.html.slim
.nested-fields
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.file_field :image

app/views/questions/destroy.js.erb
$('.delete_question').bind('ajax:success', function(){
    $(this).closest('tr').fadeOut();
});

app/views/questions/edit.html.slim
h4= 'Edit question'
= render 'form'

app/views/questions/index.html.slim
p= link_to 'Ask question', new_question_path
.questions
  - @questions.each do |question|
    .question id = "#{question.id}"
      p= question.title
      p= link_to 'Show', question
      = link_to 'Delete', question_path(question), method: :delete, :remote => true, :class => 'delete_question'

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
ruby:
  vote = @question.votes.user_vote(current_user&.id).first
  vote_kind = vote.present? ? vote.kind : ""
.question id = "#{@question.id}"
  h1= @question.title


  p= @question.body

  - if can?(:create, Subscription)
    - cache ['subscription',@question] do
      = render 'subscriptions/subscription', resource: @question
  - if current_user&.author_of?(@question)
    = link_to 'Edit question', edit_question_path(@question)
  - if current_user&.present?
    p= link_to 'Add comment', '', class: 'create-question-comment', data: { question: @question.id }
  h5= "Ссылки:"

  .comments id="comments-question-#{@question.id}"
    - @question.comments.each do |comment|
      .comment id = "comment-question-#{comment.id}"
        - cache comment do
          p = comment.body
          - if current_user&.author_of?(comment)
            = link_to "❌", comment_path(comment.id), method: :delete, remote: true
  div class='hidden' id="create-question-comment-#{@question.id}"
    - cache ['comments_nested_fields',@question] do
      p
        = render 'partials/comments_nested_fields', resource: @question, resource_type: 'question'
  - @question.links.each do |link|
    .link id = "link-#{link.id}"
      - cache link do
        p
          = link.name + ": "
          = link.link
          - if current_user&.author_of?(@question)
            = link_to "❌", link_path(link.id), method: :delete, remote: true
  p
    .vote
      - unless (vote_kind == "plus" ||  current_user&.author_of?(@question)) || !(current_user.present?)
        = link_to "➕", vote_up_question_path(id: @question.id), method: :post, remote: true, class: 'vote-plus ', id: "vote-plus-question-#{@question.id}"
      - else
        = link_to "➕", vote_up_question_path(@question.id), method: :post, remote: true, class: 'vote-plus hidden', id: "vote-plus-question-#{@question.id}"
      .vote-val id="vote-question-#{@question.id}"
        = @question.vote_result.present? ? @question.vote_result : "0"
      - unless (vote_kind == "minus" ||  current_user&.author_of?(@question)) || !(current_user.present?)
        = link_to "−",vote_down_question_path(@question.id), method: :post, remote: true, class: 'vote-minus ', id: "vote-minus-question-#{@question.id}"
      - else
        = link_to "−",vote_down_question_path(@question.id), method: :post, remote: true, class: 'vote-minus hidden', id: "vote-minus-question-#{@question.id}"
  h5= "Файлы:"

  - if @question.files.attached?
    - @question.files.each do |file|
      - cache file do
        .file id = "file-#{file.id}"
          p= link_to file.filename.to_s, url_for(file)
          - if current_user&.author_of?(@question)
            = link_to "Delete file", file_path(file.id), method: :delete, remote: true
  / - if current_user&.author_of?(@question)
  /   p= link_to 'Delete question', question_path(@question), method: :delete, class: 'btn btn-danger'
  h5= "Ответы:"

  .answers
    - cache @question.answers do
      div= render partial: '/answers/answer', collection: @question.answers

div= render 'answers/new'