config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    get 'edit_email/:id', to: 'registrations#edit_email', as: 'edit_email'
    patch 'update_email/:id', to: 'registrations#update_email', as: 'update_email'
  end
  root to: 'questions#index'
  concern :vote do
    post :vote_up, on: :member
    post :vote_down, on: :member
  end
  resources :subscriptions, only: %i[create destroy]
  resources :files, only: :destroy
  resources :links, only: %i[destroy]
  resources :comments, only: %i[create destroy]
  resources :rewards, only: %i[index]
  resources :questions, concerns: [:vote], shallow: true do
    resources :answers, concerns: [:vote], only: %i[create update destroy] do
      patch :best, on: :member
      patch :reward, on: :member
    end
  end
  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create], shallow: true do
        resources :answers, only: %i[index show create]
      end
    end
  end
  get 'search', to: 'search#index'
  # mount ActionCable.server => '/cable'
end

app/views/shared/_errors.html.slim
-if resource.errors.present?
  b "#{resource.errors.count} error(s) detected:"
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_user_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a.navbar-brand href="#"  Stack replica
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item.active
        = link_to 'Home', questions_path, class: "nav-link"
    ul.navbar-nav.mr-auto
      li.nav-item.active
       = form_tag search_path, method: :get do
         =text_field :search,:q
         = select("search", "type",%i[Question Answer Comment User], { include_blank: true , :prompt => 'Select'})

    .form-inline.my-2.my-lg-0
      - if user_signed_in?
        p= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-warning ml-2 mr-2"
        p= link_to 'Rewards', rewards_path
      - else
        p= link_to 'Sign in', new_user_session_path, class: "btn btn-info ml-2 mr-2"
        p= link_to 'Sign up', new_user_registration_path, class: "btn btn-info ml-2 mr-2"