config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    get 'edit_email/:id', to: 'registrations#edit_email', as: 'edit_email'
    patch 'update_email/:id', to: 'registrations#update_email', as: 'update_email'
  end
  root to: 'questions#index'
  concern :vote do
    post :vote_up, on: :member
    post :vote_down, on: :member
  end
  resources :subscriptions, only: %i[create destroy]
  resources :files, only: :destroy
  resources :links, only: %i[destroy]
  resources :comments, only: %i[create destroy]
  resources :rewards, only: %i[index]
  resources :questions, concerns: [:vote], shallow: true do
    resources :answers, concerns: [:vote], only: %i[create update destroy] do
      patch :best, on: :member
      patch :reward, on: :member
    end
  end
  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create], shallow: true do
        resources :answers, only: %i[index show create]
      end
    end
  end
  get 'search', to: 'search#index'
  # mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  has_many :votes, dependent: :destroy, as: :votable
  belongs_to :user
  belongs_to :question, touch: true
  has_many_attached :files

  has_many :links, dependent: :destroy, as: :linkable
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  has_many :comments, as: :commentable, dependent: :destroy
  accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
  after_create :send_email
  default_scope { order(best: 'desc').order(created_at: 'asc') }
  validates :body, presence: true
  def best_answer_false
    answer = question.answers.find_by(best: true)
    answer.update(best: false) if answer
  end

  def vote_result
    votes.sum(:value)
  end
  private

  def send_email
    AnswerNotificationJob.perform_later(question, self) if question.subscriptions.exists?
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: %i[ create ]
  before_action :find_answer, only: %i[update destroy best reward]
  after_action :publish_answer, only: [:create]
  authorize_resource
  include Votes

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    gon.question_id = @question.id
     @answer.save

  end

  def best
    @answer.best_answer_false
    @answer.update(best: true)

  end
  def reward
    @answer.question.reward.user_id =@answer.user_id
    @answer.question.reward.save

  end
  def update
    @answer.update(answer_params)
  end

  def destroy
      @answer.destroy
  end

  private

  def answer_params
    params.require(:answer).permit(:body,files: [], links_attributes: [:_destroy, :id, :name, :link])
  end

  def find_question
    @question ||= Question.find(params[:question_id])
  end

  def find_answer
    @answer = current_user.answers.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast "questions/#{@answer.question_id}",      {
      answer: ApplicationController.render(
        partial: 'answers/answer',
        locals: {
          answer: @answer,
          current_user: current_user,
        }
      )
    }

  end
end

app/controllers/api/v1/answers_controller.rb
module Api
  module V1
    class AnswersController < Api::V1::BaseController
      authorize_resource

      def index
        render json: question.answers
      end

      def show
        render json: answer
      end

      def create
        @answer = question.answers.new(answer_params)
        answer.user = current_resource_owner
        render json: @answer
      end

      def update
        if answer.update(answer_params)
          render json: answer
        else
          head :unprocessable_entity
        end
      end

      def destroy
        head :ok if answer.destroy
      end

      private

      def answer
        @answer ||= Answer.find(params[:id])
      end

      def question
        @question ||= Question.find(params[:question_id])
      end

      def answer_params
        params.require(:answer).permit(:body)
      end
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  ruby:
    vote = answer.votes.user_vote(current_user&.id).first
    vote_kind = vote.present? ? vote.kind : ""

  - if answer.persisted?
    answer id="answer-del-#{answer.id}"
      .answer id="answer-#{answer.id}"
        = answer.body
        .links id="links-#{answer.id}"
          - answer.links.each do |link|
            .link id = "link-#{link.id}"
              p
                = link.name + ": "
                = link.link
                - if current_user&.author_of?(answer)
                  = link_to "❌", link_path(link.id), method: :delete, remote: true
        .comments id="comments-answer-#{answer.id}"
          - answer.comments.each do |comment|
            .comment id = "comment-answer-#{comment.id}"
              p
                = comment.body
                - if current_user&.author_of?(comment)
                  = link_to "❌", comment_path(comment.id), method: :delete, remote: true
        p
          vote
            - unless (vote_kind == "plus" ||  current_user&.author_of?(answer)) || !(current_user.present?)
              = link_to "➕", vote_up_answer_path(answer.id), method: :post, remote: true, class: 'vote-plus ', id: "vote-plus-#{answer.id}"
            - else
              = link_to "➕", vote_up_answer_path(answer.id), method: :post, remote: true, class: 'vote-plus hidden', id: "vote-plus-#{answer.id}"
            .vote-val id="vote-#{answer.id}"
              = answer.vote_result.present? ? answer.vote_result : "0"
            - unless vote_kind == "plus" ||  current_user&.author_of?(answer) || !(current_user.present?)
              = link_to "−",vote_down_answer_path(answer.id), method: :post, remote: true, class: 'vote-minus ', id: "vote-minus-#{answer.id}"
            - else
              = link_to "−",vote_down_answer_path(answer.id), method: :post, remote: true, class: 'vote-minus hidden', id: "vote-minus-#{answer.id}"

        h2= answer.best if answer.best
      - if current_user&.author_of?(answer.question)
        p= link_to 'Reward answer', reward_answer_path(answer), method: :patch, :remote => true, :class => 'delete_answer'
      - if current_user&.author_of?(answer)
        p= link_to 'Delete answer', answer_path(answer), method: :delete, :remote => true, :class => 'delete_answer'
        p= link_to 'Best', best_answer_path(answer), method: :patch, :remote => true, class: 'answer-best', data: { answer_id: answer.id }, html: { id: "answer-best" }
      - if current_user&.present?
        p= link_to 'Add comment', '', class: 'create-answer-comment', data: { answer_id: answer.id }
      - if current_user&.author_of?(answer)
        p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
        .files id="files-#{answer.id}"
          - if answer.files.attached?
            div= render partial: '/answers/file', collection: answer.files
    = form_with model: answer, locale: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }  do |f|
      p
        = f.label :body, "Answer body", id: "body_update"
        = f.text_area :body, id: "body_update"
      p
        = f.label :files
        = f.file_field :files, multiple: true
      p
        = f.fields_for :links do |link|
          = render "partials/links_nested_fields", f: link
      p
        = link_to_add_association "Ссылки", f, "links",
                class: 'create_object',
                partial: "partials/links_nested_fields"
      .actions
        = f.submit 'Save'
    div class='hidden' id="create-answer-comment-#{answer.id}"
      p
        = render 'partials/comments_nested_fields', resource: answer, resource_type: 'answer'

app/views/answers/_file.html.slim
.file id = "file-#{file.id}"
  p
    = link_to file.filename.to_s, url_for(file)
    - if current_user&.author_of?(file.record)
      = link_to "Delete file", file_path(file.id), method: :delete, remote: true

app/views/answers/_new.html.slim
h5= 'Answer the question'
.answer-errors
  = render 'shared/errors', resource: @answer
= form_with(model: [@question, @answer], local: false) do |f|
    p
      = f.label :body, "Answer body", id: "body_create"
      = f.text_area :body, id: "body_create"
    p
      = f.label :files
      = f.file_field :files, multiple: true
      p
        = f.fields_for :links do |link|
          = render "partials/links_nested_fields", f: link
      p
        = link_to_add_association "Ссылки", f, "links",
                class: 'create_object',
                partial: "partials/links_nested_fields"
      = f.submit 'Create answer'

app/views/answers/best.js.erb
location.reload()

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
<%  if @answer.persisted? %>
//console.log('<%= j render @answer %> ')
//  $('.answers').append('<%= j render @answer %> ');
  $('#answer_body').val('');
<%end%>

app/views/answers/destroy.js.erb
answer = '<%= @answer.id %>'
var elem;
elem = document.getElementById('answer-del-' + answer);
elem.remove()

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
<%  if !@answer.errors.present? %>
var answer;
answer = '<%= @answer.id %>'
var elem;
elem = document.getElementById('answer-' + answer);
elem.innerHTML = '<%= @answer.body %>'
<%  if @answer.files.present? %>
file = '<%= @answer.id %>'
elem = document.getElementById('files-' + file);
$(elem).append('<%= j render @answer.files.last %> ');
<%end%>
<%  if @answer.links.present? %>
link = '<%= @answer.id %>'
elem = document.getElementById('links-' + link);
$(elem).append('<%= j render @answer.links.last %> ');
<%end%>
$('form#edit-answer-' + answer).addClass('hidden');

//})

<%end%>
<%  if @answer.best %>

$('form#answer-best').addClass('hidden');

//})

<%end%>